logging:
  level:
    me.silvernine: DEBUG
  file:
    path: /home/log
  logback:
    rollingpolicy:
      max-history: 7

server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/cheilsmartcare
    driver-class-name: org.mariadb.jdbc.Driver
    username: example-user
    password: my_cool_secret

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show-sql: true

  url:
    base: http://210.105.125.139
  config:
    activate:
      on-profile: prod