logging:
  level:
    root: warn
    me.silvernine: DEBUG
  file:
    path: /home/log
  logback:
    rollingpolicy:
      max-history: 7

server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/cheilsmartcare
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: rbtlrl96

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show-sql: true
        format_sql: true
    defer-datasource-initialization: true

  url:
    base: "deploy server ip"
  config:
    activate:
      on-profile: local